"""empty message

Revision ID: 2b78aaf43b8a
Revises: 55925ccf41c0
Create Date: 2025-11-07 02:53:26.964977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b78aaf43b8a'
down_revision: Union[str, Sequence[str], None] = '55925ccf41c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.alter_column('places', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
