"""empty message

Revision ID: 9f05c6d220ee
Revises: 5c28032dfa41
Create Date: 2025-11-13 01:22:07.873017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f05c6d220ee'
down_revision: Union[str, Sequence[str], None] = '5c28032dfa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_user_category')
    )
    op.add_column('user_place', sa.Column('weight', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_user_place', 'user_place', ['user_id', 'place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_place', 'user_place', type_='unique')
    op.drop_column('user_place', 'weight')
    op.drop_table('user_category')
    # ### end Alembic commands ###
